// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBR20NjRhYXHV33c9LGY8P3mJXweMPOow',
    appId: '1:452533515582:web:51992ed47756a13416286f',
    messagingSenderId: '452533515582',
    projectId: 'partner-app-4c2fb',
    authDomain: 'partner-app-4c2fb.firebaseapp.com',
    storageBucket: 'partner-app-4c2fb.appspot.com',
    measurementId: 'G-WM6SSZFV0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6X5ACLjEnTAzuLbL7mLcZDzanKXn42H4',
    appId: '1:452533515582:android:6f92672398ca40ab16286f',
    messagingSenderId: '452533515582',
    projectId: 'partner-app-4c2fb',
    storageBucket: 'partner-app-4c2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBotO-NgwC2SAV99Ouvp9eQPj3bOpCSClc',
    appId: '1:452533515582:ios:647ba9305058038a16286f',
    messagingSenderId: '452533515582',
    projectId: 'partner-app-4c2fb',
    storageBucket: 'partner-app-4c2fb.appspot.com',
    iosBundleId: 'softtech.partnerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBotO-NgwC2SAV99Ouvp9eQPj3bOpCSClc',
    appId: '1:452533515582:ios:d28375d49ea9732d16286f',
    messagingSenderId: '452533515582',
    projectId: 'partner-app-4c2fb',
    storageBucket: 'partner-app-4c2fb.appspot.com',
    iosBundleId: 'com.example.partnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBR20NjRhYXHV33c9LGY8P3mJXweMPOow',
    appId: '1:452533515582:web:8cfb3f081eaf867e16286f',
    messagingSenderId: '452533515582',
    projectId: 'partner-app-4c2fb',
    authDomain: 'partner-app-4c2fb.firebaseapp.com',
    storageBucket: 'partner-app-4c2fb.appspot.com',
    measurementId: 'G-JZNS69PSYE',
  );
}
